### ISSUE TITLE
Worker co-op weekend

### ISSUE THREAD

**Issue by jsms90** [InFact-coop/InFact#10]
Who is interested in going to the [Worker Co-op Weekend 2017](https://www.uk.coop/uniting-co-ops/events-calendar/worker-co-op-weekend-2017)?

**Date and time**
Friday, 5 May 2017 (3:00pm) - Sunday, 7 May 2017 (1:00pm)

**Location**
Foundry Adventure Centre
The Old Playhouse
Great Hucklow
Derbyshire
SK17 8RF
United Kingdom

**Price**
Camping £60.00

See https://github.com/foundersandcoders/london-programme/issues/220 

You can also see some Facsters in [this video](https://vimeo.com/194141552) of the last one

**Comment by nogainbar** [comment]
hey @jsms90 this looks really interesting but unfortunately im away that weekend...

**Comment by bradreeder** [comment]
@nogainbar coincidentally I'm also away that weekend. 😅

**Comment by jsms90** [comment]
I may be in Nazareth at this point. Looks like no one from InFact is gonna be around for this one :(

@des-des @emilyb7

**Comment by emilyb7** [comment]
shame, this looks fun!

**Comment by jsms90** [comment]
@emilyb7 I take it you're not around then either?

In which case, let's close this issue?

**Comment by emilyb7** [comment]
@jsms90 don't much feel like attending on my own!
