### ISSUE TITLE
Historical info

### ISSUE THREAD

**Issue by jsms90** [InFact-coop/InFact#17]
### Timeline
+ November (Week 5 of FAC9?) - Birth of the idea: lunch with Ines to ask about the DWYL-FAC financial (and cultural) relationship. Found out that DWYL was leaving.
+ November/December 2016 (Week 7 of FAC9?) - discussed the idea with @bradreeder & @sohilpandya. Sohil told me about the last time a FAC agency was attempted
+ Early January - my questions about FAC's funding model - https://github.com/foundersandcoders/london-programme/issues/143 & https://github.com/foundersandcoders/london-programme/issues/140
+ Dates? (between weeks 12-16 of FAC9) - reached out to others who might share the same vision, whilst keeping our numbers realistic: @sohilpandya @nogainbar @des-des (more experienced than current students)
+ January 21st - Founders and Coders AGM - met Rebecca, had first introduction to consensus based decision making. This was when the idea became a "coop" agency.
+ January 25th - met Ian Bellchambers at an [International Tech for Good meetup](https://www.meetup.com/techforgood/events/236415497/) (@jsms90). Invitation to come in to Outlandish & discuss ideas
+ Date? - Met with Dan & Ines to ask for their input / advice on us forming an agency & whether I could shadow Ines at DWYL (@bradreeder & @jsms90)
+ Most Sundays during February - brainstorming and some light research (@bradreeder & @jsms90)
+ 14th February - met with Outlandish at their offices (@bradreeder & @jsms90)
+ 16th February - invited by Outlandish to Open Tech's [post-conference networking drinks](https://2017.open.coop/sessions/networking-drinks/) (@bradreeder & @jsms90)
+ End of March - reached out to others who might share the same vision: @emilyb7 & Marko (recent graduates)
+ 22nd March - Agency formation meeting (@sohilpandya @bradreeder @jsms90 @nogainbar @des-des @emilyb7 @sofer Marko)
+ 23rd March - [Freeing the freelancer: cooperative solutions](https://www.eventbrite.com/e/freeing-the-freelancer-cooperative-solutions-tickets-32497707518#) by Altgen, at NewSpeak House (@nogainbar & @jsms90)

### 14th February - Bradley & Jen brainstorming
**Right after meeting with Outlandish**

Mission:
+ Sustain the FAC community - financially & culturally (ethos)
+ Facilitate the emergence of a cooperative ecosystem (FAC is the roots, we are the trunk, outside organisations are the branches/leaves)
+ Sustain ecosystem once created. 
+ Provide clear pathway for students who wish to remain in this ecosystem post-education
+ Grow / enable democratic education in tech

Principles:
+ Continuation of FAC values
  + _learning culture_ - applied to each project & learning points communicated through the org i.e. between projects
  + open sourcing our model (how we set this up) e.g. [Loomio coop handbook](https://loomio.coop/) or [Outlandish blog](https://outlandish.com/blog/)
  + open sourcing our learning material e.g. DWYL's "learn-xyz" repos
+ How to run the organisation: iterative improvements through use of a pattern language. Applying a scientific method to improvements by recognising good / bad patterns.
+ Process: agile
+ Open-source
+ Co-operative principles
+ Self-development: e.g. personal development plans, objectives and key results. see [outlandish](http://outlandish.com/blog/performance-management-in-an-anarcho-communist-organisation/)
+ Design / project choice: user-centric
+ Conducting work:
  + There has to be consensus on what companies / projects we take on. Everyone has the choice to work on / not work on a provided project.
  + For 5 people, we will never send all but one  
e.g. if we have 5 members, rather than taking 1 project that requires 4 people, we find 2 projects that require 2 or 3 people

Questions:
+ What kind of projects will we take on? Guidelines?
+ How important is it to take on new graduates from FAC?
+ How do we split the income?  
Work out what each member needs & charge accordingly vs. charge market rate?  
All profits go into a communal pot, then... Divide all income between all members? Divide project income between those who worked on that project? Divide equally vs. dependent on which job you do? Divide by no. of hours worked?

**Comment by jsms90** [comment]
### The formation of this agency - discussion for a FAC business meeting
**I wrote this on January 22nd, but decided this wasn't the best approach to starting the agency**

"
This is not a proposal, but an idea for discussion. I would need a lot of advice, but first I want to understand whether there is a desire for this within our community, and particularly whether there is a desire for this model.
### Why?
FAC's vision is not only to build a community for 16 weeks, but to **"establish"** this community i.e. build something that lasts for a long time. FAC was essentially born out of a desire to disrupt the education system, because of the deep-set inadequacies that were perceived in that system. Education should not be a job factory. It should not be based on getting the right answers and the right grades. It should be based on learning. It should be based on community. _FAC needs, not only a school, but an entire eco-system that enables its vision._
1. **The school needs in-house alumni**
In order to stay in line with FAC's mission statement of "building democratically organised learning communities", we need to provide a viable option for FAC graduates to remain in the space. Although many employed graduates remain active members of the organisation, the school relies heavily on the technical expertise and experience provided by its in-house alumni.
The 20-20-20 rule could not exist unless the previous cohort were full-time, or we have alumni. Project presentations are better off with input and code reviews from the alumni. Talks, whiteboard sessions, Q&A, project demonstrations don't have to be the domain of recent graduates alone.
2. **FAC has a responsibility to its students, to help them into the opportunity that is best for _them_.**
As an authority figure, FAC's advice will be listened to and asked for, by students who want to know what they should do next. Wherever possible, we should be enabling students to make their own, informed choice. If freelancing does not appear to be a viable option for them financially, they will seek employment. If they all seek employment, where is our community? If some remain as freelancers, why should we be doing more for those who gain employment, than we are doing for those who stay with us?
If we continue indefinitely on our current trajectory, FAC will be working against itself financially unless it is encouraging its students into employment with one of hiring partners. We may only need half of each cohort to choose this route in order to cover our costs #143, but we would be foolish not to broadcast this option to all students throughout the course. Pooling our resources into making employment a viable option can and will make students more likely to choose this option. _Our funding model will inevitably have an effect on the message that we send, and on the routes that students will see as available to them._
3. **We can't expect money unless we are providing opportunities**
We should not reasonably expect to get a recruitment fee, if we are not actively supplying students with the benefits that a recruitment agency offers. That is why Dan's focus has been on building relationships with employers. Students will choose to find employment through us if they believe that they are getting something through us that they could not get without us - connections & experience in order to filter out the "good" from the "bad" employers.
In just the same way, we cannot reasonably expect graduates who become independent freelancers to then pay us a portion of their fees, unless we play a role in finding them this work through our connections and experience. If we are not providing opportunities, we cannot expect remuneration.
Many of us may be so grateful for the experience, that we feel compelled to donate money back into the organisation. But it is my personal belief that _expecting_ gratitude is toxic. Students are not getting this education from us for free. They pay with the time and the work that they put in - 4 months of their lives full-time, and more than that for the chance to attend (pre-reqs). I consider it a serious mistake to imply that after that, they _should_ be grateful for everything that they get.

### What?
Just as the school is democratically-led, so too should the agency be democratically-led, hence the co-operative model. The way that the agency is run should be entirely in line with FAC's mission statement, in order to create this ecosystem of "learning communities".

But they should be two separate entities, that have two relatively distinct reasons for existing.

**Comment by jsms90** [comment]
### Timeline of external meetings
+ January 25th  
I met Ian Bellchambers at an [International Tech for Good meetup](https://www.meetup.com/techforgood/events/236415497/) - invitation to come in to Outlandish & discuss our ideas
+ 14th February - met with Outlandish (@bradreeder & @jsms90)
+ 16th February - invited by Outlandish to Open Tech's post-conference [networking drinks](https://2017.open.coop/sessions/networking-drinks/) (@bradreeder & @jsms90)
+ [Freeing the freelancer: cooperative solutions](https://www.eventbrite.com/e/freeing-the-freelancer-cooperative-solutions-tickets-32497707518#) by Altgen, at NewSpeak House (@nogainbar & @jsms90)

**Comment by jsms90** [comment]
@bradreeder Have I forgotten anything from the timeline? Or anything else that we documented?

**Comment by bradreeder** [comment]
@jsms90 Nope, not that I can see.
