### ISSUE TITLE
building a coop - applications for support

### ISSUE THREAD

**Issue by jsms90** [InFact-coop/InFact#19]
Potential support from:
+ [Altgen](http://altgen.coop/) - we already know Constance
+ [The Hive](https://www.uk.coop/the-hive/)
+ [Seeds for Change](http://www.seedsforchange.org.uk/) - mentioned by Sion at the "Freeing the freelancer: cooperative solutions" event (see separate issue #11 for Sion/Calverts)

+ [Co-operatives UK](https://www.uk.coop/developing-co-ops/start-co-operative) - [London Co-op](https://ldn.coop/start-a-co-op/start-a-worker-co-op/)
+ [Stir to Action](https://www.stirtoaction.com/workshops)
+ [Cooperative Technologists](https://www.coops.tech/) - started by Outlandish as "the [Megazord](https://outlandish.com/blog/co-op-of-software-co-ops-arise-er-megazord/)"

**Comment by nogainbar** [comment]
@jsms90 shall we assign - date, time and people which are up for meeting and writing the application forms for both Seeds for change and The Hive? 

I am OK at writing applications but not sure its my forte.. Does anyone of you feel like they totally rock at this stuff? @jsms90 @bradreeder @sohilpandya @emilyb7? its all about framing it and telling our story/narrative...

**Comment by jsms90** [comment]
@nogainbar Agreed. I was just thinking about how this issue isn't very easy to close off, and we're going to start having a huge list if we're not careful.

Maybe we could pop this into a document instead.

**Comment by emilyb7** [comment]
@nogainbar more than happy to help with the application stuff! Don't know that it's my forte either, but I'm sure that together we can do a great job ;)

**Comment by nogainbar** [comment]
I am going to reopen the issue and call it differently "help wanted with applications"

**Comment by jsms90** [comment]
@nogainbar Just opened an issue specific to The Hive #24 . Let's make these small and granular, and close-able? :+1:

**Comment by nogainbar** [comment]
oky dok
