### ISSUE TITLE
May 23rd agenda - lunchtime 13-14pm

### ISSUE THREAD

**Issue by nogainbar** [InFact-coop/InFact#34]
Facilitator: @sohilpandya 
Time keeper: @nogainbar
Other roles: TBC

Agenda

- Anna Freud Project - is it going forward? if yes than - Team availability + composition, confirmation of budget #21

- Getting the work in: more coop projects, decide on strategies for getting work in #35 

- NHS PROJECT: #22 
  - Dates for workshop
  - Dates for start of design and development in August
  - team composition
  - budget planning
  - structure of user testing sessions to communicate to Imogen

- Coop advice and funding: must reply to Sion ASAP
  - applying to the hive #24 
  - applying to Bright ideas #25

**Comment by jsms90** [comment]
Thanks for doing that @nogainbar!! Looking forward to updates :grin:

**Comment by des-des** [comment]
Yay :taco:

**Comment by jsms90** [comment]
Apparently Mark is coming to this lunchtime meeting.

So I suggest that we move the rest of this agenda to a different date & time, as we are unlikely to discuss anything other than item 1 on this agenda.

**Comment by emilyb7** [comment]
why is mark coming to our meeting? we should arrange another meeting asap, there's stuff on this agenda that's kind of time sensitive.
