### ISSUE TITLE
Let's buy a domain name

### ISSUE THREAD

**Issue by emilyb7** [InFact-coop/InFact#36]
Vote for your fave option below

**Comment by emilyb7** [comment]
infactcoop.com

**Comment by emilyb7** [comment]
infact-coop.com (£0.99 for the first year)

**Comment by emilyb7** [comment]
infact-coop.io (£46 for the first year)

**Comment by des-des** [comment]
is infact.coop available?

**Comment by emilyb7** [comment]
@des-des yes, but it's expensive 😬 http://www.domains.coop/register-coop/prices-uk/

**Comment by des-des** [comment]
:sob:

**Comment by sohilpandya** [comment]
@emilyb7 @des-des I like the .com ones. 👍 Which one? Should we put it out to a wider audience?

**Comment by nogainbar** [comment]
@emilyb7 @des-des @sohilpandya Im for infactcoop.com!

**Comment by nogainbar** [comment]
isnt the dash in infact-coop.com considered harder for the user to remember? ive never looked into the UX of domain names... 🤔

**Comment by sohilpandya** [comment]
I agree with you @nogainbar

**Comment by emilyb7** [comment]
have purchased infactcoop.com at the cost of £8. See https://github.com/InFact-coop/our-site/issues/7

 not going to press this as it's not a lot of money but donations to me are welcome.

**Comment by jsms90** [comment]
Since the question of who is a member is slightly blurry at the moment, I suggest that we start keeping a record of expenses for now?

We may need to consider reimbursement for individuals once we get money in from our first project?

**Comment by emilyb7** [comment]
yay we're online

Jen, I agree that we need a structure for tracking expenses etc.

However, I can imagine it'll be a long time until we have any money to spare, perhaps a few months. And that all needs it's own issue.

In the meantime we're talking about £8 - a small but worthwhile investment in my opinion, in that I hope it brings me work.

'Member' or not, if you feel like you stand to gain from the existence of our website, please make a contribution.

However, it's really not a big deal. Consider the domain name a gift from me to you all. Hopefully by the time we come to renew, we'll have a more functioning business model.
